Resources:
  # Task Definition
  YummlyECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: Yummly
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: '256'
      Memory: '512'
      ExecutionRoleArn: arn:aws:iam::371815123890:role/InfraBase-ExecutionRole-37sMbNnfBodD  
      TaskRoleArn: arn:aws:iam::371815123890:role/InfraBase-TaskRole-OlWl6JdyH1Q9           
      ContainerDefinitions:
        - Name: Yummly
          Image: 371815123890.dkr.ecr.us-east-1.amazonaws.com/yummly-serving:latest
          Memory: 512
          Cpu: 256
          Essential: true
          PortMappings:
            - ContainerPort: 8080
          LogConfiguration:                       
            LogDriver: awslogs
            Options:
              awslogs-group: Logs       
              awslogs-region: us-east-1           
              awslogs-stream-prefix: Yummly

  # ECS Service
  YummlyECSService:
    Type: AWS::ECS::Service
    DependsOn: 
      - YummlyALBListener
    Properties:
      Cluster: InfraBase-ECSCluster-LGxtNiUvnwOO
      LaunchType: FARGATE
      PlatformVersion: '1.3.0'
      DesiredCount: 1
      TaskDefinition: !Ref YummlyECSTaskDefinition
      LoadBalancers:
        - ContainerName: Yummly
          ContainerPort: 8080
          TargetGroupArn: !Ref YummlyALBTargetGroup
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - subnet-0e2b48d919c240b3f 
            - subnet-0204ab161c2fd6926
          SecurityGroups:
            - sg-0c659425934fb655b
            - sg-03076ea8a1a229cee
      DeploymentController: 
        Type: ECS
      HealthCheckGracePeriodSeconds: 60
      ServiceConnectConfiguration:
        Enabled: false

  # ALB
  YummlyALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      Name: YummlyALB
      Type: application
      Subnets: 
        - subnet-0e2b48d919c240b3f 
        - subnet-0204ab161c2fd6926  
      SecurityGroups: 
        - sg-0c659425934fb655b
        - sg-03076ea8a1a229cee

  # Listener
  YummlyALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn: 
      - YummlyALB
      - YummlyALBTargetGroup
    Properties: 
      DefaultActions: 
        - Type: forward
          TargetGroupArn: !Ref YummlyALBTargetGroup
      LoadBalancerArn: !Ref YummlyALB
      Port: 443        
      Protocol: HTTPS
      Certificates:
        - CertificateArn: arn:aws:acm:us-east-1:371815123890:certificate/880823b2-936a-4194-9060-28e2dfa7341a

  # ALB Target Group
  YummlyALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: YummlyALB
    Properties:
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      HealthCheckPath: /api/v1/ping
      HealthCheckProtocol: HTTP
      VpcId: vpc-0abd5e319f3b8bb9e

  
