Resources:
  # Task Definition
  YummlyECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: Yummly
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: '256'
      Memory: '512'
      ExecutionRoleArn: arn:aws:iam::371815123890:role/InfraBase-ExecutionRole-37sMbNnfBodD  
      TaskRoleArn: arn:aws:iam::371815123890:role/InfraBase-TaskRole-OlWl6JdyH1Q9           
      ContainerDefinitions:
        - Name: yummly-db
          Image: postgres
          Essential: true
          Memory: 256
          Cpu: 128
          Environment:
            - Name: POSTGRES_PASSWORD
              Value: base1234
            - Name: POSTGRES_DB
              Value: daidb
          PortMappings:
            - ContainerPort: 5432
          LogConfiguration:                       
            LogDriver: awslogs
            Options:
              awslogs-group: Logs       
              awslogs-region: us-east-1           
              awslogs-stream-prefix: YummlyDB
        - Name: yummly-app
          Image: 371815123890.dkr.ecr.us-east-1.amazonaws.com/yummly-serving:latest
          Essential: true
          Memory: 256
          Cpu: 128
          PortMappings:
            - ContainerPort: 8080
          Environment:
            - Name: CODE
              Value: superSecret
            - Name: POSTGRES_DB
              Value: daidb
            - Name: POSTGRES_USER
              Value: postgres
            - Name: POSTGRES_PASSWORD
              Value: base1234
            - Name: POSTGRES_HOST
              Value: localhost
            - Name: POSTGRES_PORT
              Value: 5432
          LogConfiguration:                       
            LogDriver: awslogs
            Options:
              awslogs-group: Logs       
              awslogs-region: us-east-1           
              awslogs-stream-prefix: Yummly

  # ECS Service
  YummlyECSService:
    DependsOn: 
      - YummlyALB
      - YummlyALBTargetGroup
    Type: AWS::ECS::Service
    Properties:
      Cluster: InfraBase-ECSCluster-LGxtNiUvnwOO
      LaunchType: FARGATE
      PlatformVersion: '1.3.0'
      DesiredCount: 1
      LoadBalancers:
        - ContainerName: yummly-app
          ContainerPort: 8080
          TargetGroupArn: !Ref YummlyALBTargetGroup
      TaskDefinition: !Ref YummlyECSTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - subnet-0e2b48d919c240b3f 
            - subnet-0204ab161c2fd6926
          SecurityGroups:
            - sg-0c659425934fb655b
            - sg-03076ea8a1a229cee
      DeploymentController: 
        Type: ECS
      ServiceConnectConfiguration:
        Enabled: false

  # ALB
  YummlyALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      Name: YummlyALB
      Type: application
      Subnets: 
        - subnet-0e2b48d919c240b3f 
        - subnet-0204ab161c2fd6926  
      SecurityGroups: 
        - sg-0c659425934fb655b
        - sg-03076ea8a1a229cee

  # ALB Target Group
  YummlyALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    DependsOn: 
      - YummlyALB
    Properties:
      Port: 8080
      Protocol: HTTP
      TargetType: ip
      HealthCheckPath: /ping
      HealthCheckProtocol: HTTP
      VpcId: vpc-0abd5e319f3b8bb9e

  # Listener
  YummlyALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    DependsOn: 
      - YummlyALB
      - YummlyALBTargetGroup
    Properties: 
      DefaultActions: 
        - Type: forward
          TargetGroupArn: !Ref YummlyALBTargetGroup
      LoadBalancerArn: !Ref YummlyALB
      Port: 443        
      Protocol: HTTPS
      Certificates:
        - CertificateArn: arn:aws:acm:us-east-1:371815123890:certificate/cbcf4f53-a658-4b95-b4e2-7c54ee84d289
