const recipesData = [
    {
      title: 'Paella Vegetariana',
      description: "description",
      preparationTime: "preparationTime",
      servingCount: 1,
      ingredients: "ingredients",
      steps: "steps",
      calories: 10,
      totalFats: 1.0,
      proteins: 1.0,
      image: 'https://s3.abcstatics.com/media/gurmesevilla/2012/01/comida-rapida-casera.jpg',
      tags: [ 'VEGANA', 'ANTIINFLAMATORIA']
    },
    {
      title: 'Tacos Veganos de Jackfruit',
      description: "description",
      preparationTime: "preparationTime",
      servingCount: 1,
      ingredients: "ingredients",
      steps: "steps",
      calories: 10,
      totalFats: 1.0,
      proteins: 1.0,
      image: 'https://static-cse.canva.com/blob/598703/Fotografiadecomida.jpg',
      tags: [ 'VEGANA', 'APTAS_CELIACAS']
    },
    {
      title: 'Café de Cebada con Especias',
      description: "description",
      preparationTime: "preparationTime",
      servingCount: 1,
      ingredients: "ingredients",
      steps: "steps",
      calories: 10,
      totalFats: 1.0,
      proteins: 1.0,
      image: 'https://www.recetasnestle.com.ar/sites/default/files/2022-06/ingredientes-comida-de-mar-parrilla.jpg',
      tags: [ 'SISTEMAS_INMUNE', 'ANTIINFLAMATORIA']
    },
    {
      title: 'Ensalada Mediterránea con Quinoa',
      description: "description",
      preparationTime: "preparationTime",
      servingCount: 1,
      ingredients: "ingredients",
      steps: "steps",
      calories: 10,
      totalFats: 1.0,
      proteins: 1.0,
      image: 'https://www.elmueble.com/medio/2023/05/23/tacos_fcb4f631_00541381_230523124558_1500x2032.jpg',
      tags: ['BAJA_CARBOHIDRATOS', 'BAJA_SODIO']
    },
    {
      title: 'Bowl de Açaí y Frutas',
      description: "description",
      preparationTime: "preparationTime",
      servingCount: 1,
      ingredients: "ingredients",
      steps: "steps",
      calories: 10,
      totalFats: 1.0,
      proteins: 1.0,
      image: 'https://cdn.aarp.net/content/dam/aarp/health/caregiving/2018/03/1140-nutrients-food-loved-ones-caregiving-esp.jpg',
      tags: ['SISTEMAS_INMUNE', 'VEGETARIANA']
    },
    {
      title: 'Helado de Aguacate y Coco',
      description: "description",
      preparationTime: "preparationTime",
      servingCount: 1,
      ingredients: "ingredients",
      steps: "steps",
      calories: 10,
      totalFats: 1.0,
      proteins: 1.0,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkGTV9ptpoJ1nv8SE8QJ_A4-pCjnd46axWiA&usqp=CAU',
      tags: ['APTAS_CELIACAS', 'FLORA_INTESTINAL']
    },
    {
      title: 'Sopa de Maní Tradicional',
      description: "description",
      preparationTime: "preparationTime",
      servingCount: 1,
      ingredients: "ingredients",
      steps: "steps",
      calories: 10,
      totalFats: 1.0,
      proteins: 1.0,
      image: 'https://www.laylita.com/recetas/wp-content/uploads/2023/08/Receta-de-la-sopa-de-mani.jpg',
      tags: [ 'VEGETARIANA', 'RAPIDA_PREPARACION']
    },
    {
      title: 'Carne Asada con Chimichurri',
      description: "description",
      preparationTime: "preparationTime",
      servingCount: 1,
      ingredients: "ingredients",
      steps: "steps",
      calories: 10,
      totalFats: 1.0,
      proteins: 1.0,
      image: 'https://img.freepik.com/foto-gratis/primer-plano-carne-asada-salsa-verduras-patatas-fritas-plato-sobre-mesa_181624-35847.jpg',
      "cta": 'Ver receta',
      tags: ['VEGANA', 'APTAS_CELIACAS']
    },
    {
      title: 'Gazpacho Andaluz Refrescante',
      description: "description",
      preparationTime: "preparationTime",
      servingCount: 1,
      ingredients: "ingredients",
      steps: "steps",
      calories: 10,
      totalFats: 1.0,
      proteins: 1.0,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_wulETjl6TbYZ3Z4M088Gn3BDvEPhVmYiTQ&usqp=CAU',
      tags: [ 'SISTEMAS_INMUNE', 'FLORA_INTESTINAL']
    },
    {
      title: 'Curry Vegano de Lentejas',
      description: "description",
      preparationTime: "preparationTime",
      servingCount: 1,
      ingredients: "ingredients",
      steps: "steps",
      calories: 10,
      totalFats: 1.0,
      proteins: 1.0,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4FR8wrs9_0hB3XpxnrggBXRjt1D6F2cLOqQ&usqp=CAU',
      tags: ['ANTIINFLAMATORIA', 'BAJA_CARBOHIDRATOS']
    },
    {
      title: 'Tortilla Española Clásica',
      description: "description",
      preparationTime: "preparationTime",
      servingCount: 1,
      ingredients: "ingredients",
      steps: "steps",
      calories: 10,
      totalFats: 1.0,
      proteins: 1.0,
      image: 'https://www.recetasnestle.com.co/sites/default/files/inline-images/comidas-fritas-plato-apanado-ensalada.jpg',
      tags: ['BAJA_SODIO', 'VEGETARIANA']
    },
    {
      title: 'Empanadas de Carne Cortada a Cuchillo',
      description: "description",
      preparationTime: "preparationTime",
      servingCount: 1,
      ingredients: "ingredients",
      steps: "steps",
      calories: 10,
      totalFats: 1.0,
      proteins: 1.0,
      image: 'https://www.gastronomiaycia.com/wp-content/uploads/2021/01/elplatoharvard_2-680x448.jpg',
      tags: [ 'RAPIDA_PREPARACION', 'VEGANA']
    },
    {
      title: 'Ceviche Peruano de Pescado',
      description: "description",
      preparationTime: "preparationTime",
      servingCount: 1,
      ingredients: "ingredients",
      steps: "steps",
      calories: 10,
      totalFats: 1.0,
      proteins: 1.0,
      image: 'https://img.europapress.es/fotoweb/fotonoticia_20180117114451_1200.jpg',
      tags: [ 'APTAS_CELIACAS', 'SISTEMAS_INMUNE']
    },
    {
      title: 'Pollo al Horno con Hierbas',
      description: "description",
      preparationTime: "preparationTime",
      servingCount: 1,
      ingredients: "ingredients",
      steps: "steps",
      calories: 10,
      totalFats: 1.0,
      proteins: 1.0,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrgUcf2pA82UbEWGZy53h2SblBfjuh7HbSidmopFmeV8vxEGZmZWSJZ1YmcxNZN_Hdz9M&usqp=CAU',
      tags: ['FLORA_INTESTINAL', 'ANTIINFLAMATORIA']
    },
    {
      title: 'Risotto de Setas Silvestres',
      description: "description",
      preparationTime: "preparationTime",
      servingCount: 1,
      ingredients: "ingredients",
      steps: "steps",
      calories: 10,
      totalFats: 1.0,
      proteins: 1.0,
      image: 'https://www.cocinacaserayfacil.net/wp-content/uploads/2020/04/Recetas-de-comidas-para-ni%C3%B1os.jpg',
      tags: [ 'BAJA_CARBOHIDRATOS', 'BAJA_SODIO']
    },
    {
      title: 'Crema de Calabaza y Zanahoria',
      description: "description",
      preparationTime: "preparationTime",
      servingCount: 1,
      ingredients: "ingredients",
      steps: "steps",
      calories: 10,
      totalFats: 1.0,
      proteins: 1.0,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTm7KZl79yp8Hh8WOP8aRcoTYzaf3_xpXxEA&usqp=CAU',
      tags: [ 'VEGETARIANA', 'RAPIDA_PREPARACION']
    },
    {
      title: 'Chiles en Nogada Estilo Gourmet',
      description: "description",
      preparationTime: "preparationTime",
      servingCount: 1,
      ingredients: "ingredients",
      steps: "steps",
      calories: 10,
      totalFats: 1.0,
      proteins: 1.0,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSLWNBIqTtuhQjtMtQZ0JZYECLVb0f4JokSg&usqp=CAU',
      tags: [ 'RAPIDA_PREPARACION', 'BAJA_CARBOHIDRATOS']
    },
    {
      title: 'Bacalao a la Vizcaína Tradicional',
      description: "description",
      preparationTime: "preparationTime",
      servingCount: 1,
      ingredients: "ingredients",
      steps: "steps",
      calories: 10,
      totalFats: 1.0,
      proteins: 1.0,
      image: 'https://images.unsplash.com/photo-1539136788836-5699e78bfc75?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cGxhdG8lMjBkZSUyMGNvbWlkYXxlbnwwfHwwfHx8MA%3D%3D',
      tags: [ 'RAPIDA_PREPARACION', 'APTAS_CELIACAS']
    },
    {
      title: 'Salpicón de Marisco Fresco',
      description: "description",
      preparationTime: "preparationTime",
      servingCount: 1,
      ingredients: "ingredients",
      steps: "steps",
      calories: 10,
      totalFats: 1.0,
      proteins: 1.0,
      image: 'https://cdn.pixabay.com/photo/2018/05/21/22/52/gourmet-food-3419926_1280.jpg',
      tags: ['carbohidratos', 'sodio']
    },
    {
      title: 'Tarta de Santiago Almendrada',
      description: "description",
      preparationTime: "preparationTime",
      servingCount: 1,
      ingredients: "ingredients",
      steps: "steps",
      calories: 10,
      totalFats: 1.0,
      proteins: 1.0,
      image: 'https://aprende.com/wp-content/uploads/2021/12/clases-online-de-chef.jpg',
      tags: [ 'ANTIINFLAMATORIA', 'RAPIDA_PREPARACION']
    }
];


module.exports = { recipesData };
